### ISSUE TITLE
Any chance of an update?

### ISSUE THREAD

**Issue by humblecoder** [jseppi/Leaflet.MakiMarkers#19]
Any chance of an update?  As of this post, Leaflet is on 1.4.0 and doesn't seem to properly load/initialize with this plugin.

**Comment by jseppi** [comment]
Hey @humblecoder - are you seeing an error of some sort?

I've updated the example `index.html` (see https://github.com/jseppi/Leaflet.MakiMarkers/commit/0e7e0431025571bbceca6308a9570e3bca189504) to use Leaflet 1.4.0 and changed the example basemap to one offered by carto.com since the previous MapQuest service is now gone.

Everything looks like it still works to me, and I didn't have to make any changes to `Leaflet.MakiMarkers.js`.

**Comment by humblecoder** [comment]
@jseppi Thanks.  I'm using VueJS and including the plugin via `import`s which should have been just fine.  I was getting errors of `L` being undefined.  I shuffled the code a bit and all is well.  Now, however, I'm having an issue with some of the icons.  Apparently not all in the list are valid.  Any links to updated icon names?

**Comment by jseppi** [comment]
I think the marker names given by https://github.com/mapbox/maki/blob/v0.5.0/_includes/maki.json should all be valid.

**Comment by humblecoder** [comment]
Thanks, those seem to work!
